package megdc

const (
	HOST_IP    = "host_ip"
	EventUser  = "user"
	EVENT_TYPE = "event_type"
	ACCOUNT_ID = "account_id"
	USERMAIL   = "email"

	TPL_HOSTINFOS_RUN      = "hostinfos.running"
	CMD_GETCONFIG_BEGIN    = "hostinfos.get_config.starting"
	CMD_GETCONFIG_END      = "hostinfos.get_config.completed"
	CMD_KVMCHECK_BEGIN     = "hostinfos.kvm_check.starting"
	CMD_KVMCHECK_END       = "hostinfos.kvm_check.completed"
	TPL_HOSTINFOS_FINISHED = "hostinfos.finished"

	TPL_VERTICE_RUN       = "vertice.running"
	VERTICE_INSTALL_BEGIN = "vertice.install.starting"
	VERTICE_INSTALL_END   = "vertice.install.completed"
	TPL_VERTICE_FINISHED  = "vertice.finished"

	TPL_VERTICEGATEWAY_RUN      = "verticegateway.running"
	GATEWAY_INSTALL_BEGIN       = "verticegateway.install.starting"
	GATEWAY_INSTALL_END         = "verticegateway.install.completed"
	TPL_VERTICEGATEWAY_FINISHED = "verticegateway.finished"

	TPL_VERTICENILAVU_RUN      = "verticenilavu.running"
	NILAVU_INSTALL_BEGIN       = "verticenilavu.install.starting"
	NILAVU_INSTALL_END         = "verticenilavu.install.completed"
	TPL_VERTICENILAVU_FINISHED = "verticenilavu.finished"

	TPL_ONEMASTER_RUN        = "onemaster.running"
	ONEMASTER_INSTALL_BEGIN  = "onemaster.install.starting"
	ONEMASTER_INSTALL_END    = "onemaster.install.completed"
	ONEMASTER_ACTIVATE_BEGIN = "onemaster.activate.starting"
	ONEMASTER_ACTIVATE_END   = "onemaster.activate.completed"
	TPL_ONEMASTER_FINISHED   = "onemaster.finished"

	TPL_ONEHOST_RUN       = "onehost.running"
	ONEHOST_PEPARE_BEGIN  = "onehost.depends_install.starting"
	ONEHOST_PREPARE_END   = "onehost.depends_install.completed"
	ONEHOST_INSTALL_BEGIN = "onehost.install.starting"
	ONEHOST_INSTALL_END   = "onehost.install.completed"
	TPL_ONEHOST_FINISHED  = "onehost.finished"

	TPL_CEPHCLUSTER_RUN          = "cephculster.running"
	CEPHCLUSTER_DEPENDS_BEGIN    = "cephculster.depends_install.starting"
	CEPHCLUSTER_DEPENDS_END      = "cephculster.depends_install.completed"
	CEPHCLUSTER_INSTALL_BEIGIN   = "cephculster.install.starting"
	CEPHCLUSTER_INSTALL_END      = "cephculster.install.completed"
	CEPHCLUSTER_ACCESS_BEGIN     = "cephculster.access_prepare.starting"
	CEPHCLUSTER_ACCESS_END       = "cephculster.access_prepare.completed"
	CEPHCLUSTER_NEW_BEGIN        = "cephculster.create_new.starting"
	CEPHCLUSTER_NEW_END          = "cephcluster.create_new.completed"
	CEPHCLUSTER_CONFIG_BEGIN     = "cephcluster.configure_changes.starting"
	CEPHCLUSTER_CONFIG_END       = "cephcluster.configure_changes.completed"
	CEPHCLUSTER_MON_BEGIN        = "cephcluster.mon_init.starting"
	CEPHCLUSTER_MON_END          = "cephcluster.mon_init.completed"
	CEPHCLUSTER_CREATEPOOL_BEGIN = "cephcluster.create_pool.starting"
	CEPHCLUSTER_CREATEPOOL_END   = "cephcluster.create_pool.completed"
	TPL_CEPHCLUSTER_FINISHED     = "cephculster.finished"

	TPL_CEPHCLIENT_RUN       = "cephclient.running"
	CEPHCLIENT_INSTALL_BEGIN = "cephclient.install.starting"
	CEPHCLIENT_INSTALL_END   = "cephclient.install.completed"
	TPL_CEPHCLIENT_FINISHED  = "cephclient.finished"

	TPL_ADDOSDS_RUN      = "addosds.running"
	OSDS_ACTIVATE_BEGIN  = "addosds.activate.starting"
	OSDS_ACTIVATE_END    = "addosds.activate.completed"
	OSDS_PREPARE_BEGIN   = "addosds.prepare.starting"
	OSDS_PREPARE_END     = "addosds.prepare.completed"
	TPL_ADDOSDS_FINISHED = "addosds.finished"

	TPL_DSCONNECTION_RUN      = "cephds.running"
	CEPHDS_AUTHKEY_BEGIN      = "cephds.create_authkey.starting"
	CEPHDS_AUTHKEY_END        = "cephds.create_authkey.completed"
	CEPHDS_DEFINEKEY_BEGIN    = "cephds.define_secretkey.starting"
	CEPHDS_DEFINEKEY_END      = "cephds.define_secretkey.completed"
	TPL_DSCONNECTION_FINISHED = "cephds.finished"

	TPL_CEPHACCESS_RUN        = "pass_pubkey.running"
	CEPHACCESS_PASSWORD_BEGIN = "pass_pubkey.using_password.starting"
	CEPHACCESS_PASSWORD_END   = "pass_pubkey.using_password.completed"
	CEPHACCESS_KEY_BEGIN      = "pass_pubkey.using_key.starting"
	CEPHACCESS_KEY_END        = "pass_pubkey.using_key.completed"
	TPL_CEPHACCESS_FINISHED   = "pass_pubkey.finished"

	TPL_ZAPDISK_RUN      = "zap_disks.running"
	ZAPDISKS_CLEAN_BEGIN = "zap_disks.clean.starting"
	ZAPDISKS_CLEAN_END   = "zap_disks.clean.completed"
	TPL_ZAPDISK_FINISHED = "zap_disks.finished"

	TPL_KVMNETWORK_RUN      = "kvm_network.running"
	KVMNETWORK_CONFIG_BEGIN = "kvm_network.configure.starting"
	KVMNETWORK_CONFIG_END   = "kvm_network.configure.completed"
	TPL_KVMNETWORK_FINISHED = "kvm_network.finished"

	TPL_LVMINSTALL_RUN      = "lvm.running"
	LVM_INSTALL_BEGIN       = "lvm.install.starting"
	LVM_INSTALL_END         = "lvm.install.completed"
	TPL_LVMINSTALL_FINISHED = "lvm.finished"

	TPL_NETWORKINFO_RUN      = "networkinfos.running"
	GETNETWORK_INFOS_BEGIN   = "networkinfos.interfaces.starting"
	GETNETWORK_INFOS_END     = "networkinfos.interfaces.completed"
	TPL_NETWORKINFO_FINISHED = "networkinfos.finished"

	PREERROR = "preerror"
	ERROR    = "error"

	OBCTEMPLATEPREERRORTYPE = "obc.template.preerror"
	OBCTEPMLATEERRORTYPE    = "obc.errors"

	INSTALLINGNILAVU     = "nilavuinstall"
	INSTALLINGGATEWAY    = "gatewayinstall"
	INSTALLINGVERTICE    = "verticeinstall"
	INSTALLINGGULPD      = "gulpdinstall"
	INSTALLINGCOMMON     = "commoninstall"
	INSTALLINGCASSSANDRA = "cassandrainstall"
	INSTALLEDNILAVU      = "nilavuinstalled"
	INSTALLEDGATEWAY     = "gatewayinstalled"
	INSTALLEDVERTICE     = "verticeinstalled"
	INSTALLEDGULPD       = "gulpdinstalled"
	INSTALLEDCOMMON      = "commoninstalled"
	INSTALLEDCASSSANDRA  = "cassandrainstalled"

	//Installing Vertice Packages statuses

	//Templates HostInfos status types
	OBCHOSTINFOSTPLRUN              = "obc.hosts.getinfos.running"
	OBCHOSTINFOSCONFIGPARSING       = "obc.hosts.get_config.parsing"
	OBCHOSTINFOSCONFIGPARSED        = "obc.hosts.get_config.parsed"
	OBCHOSTINFOSKVMCHECKPARSING     = "obc.hosts.kvm_check.parsing"
	OBCHOSTINFOSKVMCHECKPARSED      = "obc.hosts.kvm_check.parsed"
	OBCHOSTINFOSTPLFINISHED         = "obc.hosts.getinfos.finished"
	OBCVERTICETPLRUN                = "obc.vertice.engine.running"
	OBCVERTICETPLFINISHED           = "obc.vertice.engine.finished"
	OBCVERTICEINSTALLINGTYPE        = "obc.vertice.engine.installing"
	OBCVERTICEINSTALLEDTYPE         = "obc.vertice.engine.installed"
	OBCVERTICEGATEWAYTPLRUN         = "obc.vertice.gateway.running"
	OBCVERTICEGATEWAYTPLFINISHED    = "obc.vertice.gateway.finished"
	OBCVERTICEGATEWAYINSTALLINGTYPE = "obc.vertice.gateway.installing"
	OBCVERTICEGATEWAYINSTALLEDTYPE  = "obc.vertice.gateway.installed"
	OBCVERTICENILAVUTPLRUN          = "obc.vertice.nilavu.running"
	OBCVERTICENILAVUTPLFINISHED     = "obc.vertice.nilavu.finished"
	OBCVERTICENILAVUINSTALLINGTYPE  = "obc.vertice.nilavu.installing"
	OBCVERTICENILAVUINSTALLEDTYPE   = "obc.vertice.nilavu.installed"
	OBCONEMASTERTPLRUN              = "obc.one.master.running"
	OBCONEMASTERINSTALLINGTYPE      = "obc.one.master.installing"
	OBCONEMASTERINSTALLEDTYPE       = "obc.one.master.installed"
	OBCONEMASTERACTIVATINGTYPE      = "obc.one.master.activating"
	OBCONEMASTERACTIVATEDTYPE       = "obc.one.master.activated"
	OBCONEMASTERTPLFINISHED         = "obc.one.master.finished"

	OBCONEHOSTTPLRUN          = "obc.one.node.running"
	OBCONEHOSTPEPARINGTYPE    = "obc.one.node.depends_installing"
	OBCONEHOST_PREPAREDTYPE   = "obc.one.node.depends_installed"
	OBCONEHOSTINSTALLINGTYPE  = "obc.one.node.installing"
	OBCONEHOSTINSTALLEDTYPE   = "obc.one.node.installed"
	OBCONEHOSTTPLFINISHEDTYPE = "obc.one.node.finished"

	OBCCEPHCLUSTERTPLRUN                = "obc.ceph.cluster.running"
	OBCCEPHCLUSTERDEPENDSINSTALLINGTYPE = "obc.ceph.cluster.depends_installing"
	OBCCEPHCLUSTERDEPENDSINSTALLEDTYPE  = "obc.ceph.cluster.depends_installed"
	OBCCEPHCLUSTERINSTALLINGTYPE        = "obc.ceph.cluster.installing"
	OBCCEPHCLUSTERINSTALLEDTYPE         = "obc.ceph.cluster.installed"
	OBCCEPHCLUSTERACCESSENABLINGTYPE    = "obc.ceph.cluster.access_preparing"
	OBCCEPHCLUSTERACCESSENABLEDTYPE     = "obc.ceph.cluster.access_prepared"
	OBCCEPHCLUSTERNEWCREATINGTYPE       = "obc.ceph.cluster.new_creating"
	OBCCEPHCLUSTERNEWCREATEDTYPE        = "obc.ceph.cluster.new_created"
	OBCCEPHCLUSTERCONFIGURINGTYPE       = "obc.ceph.cluster.configure_changing"
	OBCCEPHCLUSTERCONFIGUREDTYPE        = "obc.ceph.cluster.configure_changed"
	OBCCEPHCLUSTERMONINITIALINGTYPE     = "obc.ceph.cluster.mon_initializing"
	OBCCEPHCLUSTERMONINITIALIZEDTYPE    = "obc.ceph.cluster.mon_initialized"
	OBCCEPHCLUSTERPOOLCREATINGTYPE      = "obc.ceph.cluster.pool_creating"
	OBCCEPHCLUSTERPOOLCREATEDTYPE       = "obc.ceph.cluster.pool_created"
	OBCCEPHCLUSTERTPLFINISHED           = "obc.ceph.cluster.finished"

	OBCCEPHCLIENTTPLRUN      = "obc.ceph.client.running"
	OBCCEPHCLIENTINSTALLING  = "obc.ceph.client.installing"
	OBCCEPHCLIENTINSTALLED   = "obc.ceph.client.installed"
	OBCCEPHCLIENTTPLFINISHED = "obc.ceph.client.finished"

	OBCADDOSDSTPLRUN      = "obc.ceph.addosds.running"
	OBCOSDSACTIVATINGTYPE = "obc.ceph.addosds.activating"
	OBCOSDSACTIVATEDTYPE  = "obc.ceph.addosds.activated"
	OBCOSDSPREPARINGTYPE  = "obc.ceph.addosds.prepareing"
	OBCOSDSPREPAREDTYPE   = "obc.ceph.addosds.prepared"
	OBCADDOSDSTPLFINISHED = "obc.ceph.addosds.finished"

	OBCCEPHDSCONNECTIONTPLRUN      = "obc.ceph.datastore.running"
	OBCCEPHDSAUTHKEYCREATINGTYPE   = "obc.ceph.datastore.authkey_creating"
	OBCCEPHDSAUTHKEYCREATEDTYPE    = "obc.ceph.datastore.authkey_created"
	OBCCEPHDSAUTHKEYDEFININGTYPE   = "obc.ceph.datastore.secretkey_defining"
	OBCCEPHDSAUTHKEYDEFINEDTYPE    = "obc.ceph.datastore.secretkey_defined"
	OBCCEPHDSCONNECTIONTPLFINISHED = "obc.ceph.datastore.finished"

	OBCCEPHACCESSTPLRUN                 = "obc.ceph.pass_pubkey.running"
	OBCCEPHACCESSPASSAUTHENDICATINGTYPE = "obc.ceph.pass_pubkey.password_authendicating"
	OBCCEPHACCESSPASSAUTHENDICATEDTYPE  = "obc.ceph.pass_pubkey.password_authendicated"
	OBCCEPHACCESSKEYAUTHENDICATINGTYPE  = "obc.ceph.pass_pubkey.key_authendicating"
	OBCCEPHACCESSKEYAUTHENDICATEDTYPE   = "obc.ceph.pass_pubkey.key_authendicated"
	OBCCEPHACCESSTPLFINISHED            = "obc.ceph.pass_pubkey.finished"

	OBCZAPDISKTPLRUN        = "obc.ceph.zap_disks.running"
	OBCZAPDISKSCLEANINGTYPE = "obc.ceph.zap_disks.cleaning"
	OBCZAPDISKSCLEANEDTYPE  = "obc.ceph.zap_disks.cleaned"
	OBCZAPDISKTPLFINISHED   = "obc.ceph.zap_disks.finished"

	OBCKVMNETWORKTPLRUN          = "obc.network.kvm.running"
	OBCKVMNETWORKCONFIGURINGTYPE = "obc.network.kvm.configuring"
	OBCKVMNETWORKCONFIGUREDTYPE  = "obc.network.kvm.configured"
	OBCKVMNETWORKTPLFINISHED     = "obc.network.kvm.finished"

	OBCLVMTPLRUN          = "obc.lvm.setup.running"
	OBCLVM_INSTALLINGTYPE = "obc.lvm.package.starting"
	OBCLVMINSTALLEDTYPE   = "obc.lvm.package.completed"
	OBCLVMTPLFINISHED     = "obc.lvm.setup.finished"

	OBCNETWORKINFOTPLRUN            = "obc.network.infos.running"
	OBCGETNETWORKINFOSGATHERINGTYPE = "obc.network.infos.gathering"
	OBCGETNETWORKINFOSGATHEREDTYPE  = "obc.network.infos.gathered"
	OBCNETWORKINFOTPLFINISHED       = "obc.network.infos.finished"
)
